# This is a basic workflow to help you get started with Actions

# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
    watch:
     types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  # This workflow contains a single job called "build"
  build:
    needs: [authorize]
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    if: github.actor == aniruddhag-gdb

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true

    # Runs a set of commands using the runners shell
    - name: Run a Build script
      run: |
        cd src
        mkdir out
        javac Hello.java -d out/
        cd out
        java Hello
    
    - name: get commid id for the Build
      run: echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-12)
