# This is a basic workflow to help you get started with Actions

name: dev-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
   repository_dispatch:
    types: generate-build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #if: "contains(github.event.commits[0].message, '[generate-daily-build]')"  
    runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
        
    - name: Get Latest Build number, Version, Git sha
      run: |
        echo ::set-env name=BUILD_INFO::${{ github.event.client_payload.version }}-$(echo $GITHUB_SHA | cut -c 1-12)-${{ github.event.client_payload.buid }}
           
    - name : Generating Build ${{ env.BUILD_INFO }}
      run: echo ${{ env.BUILD_INFO }}
    
    # Runs a set of commands using the runners shell
    - name: Run a Build script
      run: |
        cd src
        mkdir out
        javac Hello.java -d out/
        cd out
        java Hello
      
    - name: Creating a distribution zip
      run: |
        cd src
        mv out ${{ env.BUILD_INFO }}
        zip -r ${{ env.BUILD_INFO }}.zip ${{ env.BUILD_INFO }}
